# Generated by Django 4.2 on 2023-05-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('acode', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
                ('re_password', models.CharField(max_length=15)),
                ('textarea', models.CharField(max_length=100)),
                ('checkbox', models.CharField(max_length=50)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('agree', models.BooleanField()),
            ],
        ),
    ]
